[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.lua]
command = "stylua"
includes = ["*.lua"]

[formatter.toml]
command = "tombi"
options = ["format"]
includes = ["*.toml"]
